# Generated by Django 5.2.1 on 2025-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
