# Generated by Django 5.2.1 on 2025-05-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_unit_enrollment_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
